### ISSUE TITLE
add binary driver for images, videos and other binary files

### ISSUE THREAD

**Issue by Gummibeer** [spatie/phpunit-snapshot-assertions#102]
Hey,

I have some controller actions returning authorization protected binary files (image, video) or runtime generated binary content (image, zip).
It would be cool if there would be a `BinaryDriver` which accepts the wanted extension as construct argument. So I would be able to do this:

```php
$this->assertMatchesBinarySnapshot($image, 'jpg');
```

And it matches with `Test__test_image__1.jpg` snapshot file.

**Comment by fgilio** [comment]
This would be pretty handy

**Comment by freekmurze** [comment]
We'd accept a PR that adds this 👍

**Comment by Gummibeer** [comment]
I'm on it - just waited for the go. 🚀

**Comment by Gummibeer** [comment]
After digging through current source I've found that `assertMatchesFileSnapshot($file)` does exactly this.
So I will close this issue because it's already implemented.
