### ISSUE TITLE
Default to `without-creating-snapshots`

### ISSUE THREAD

**Issue by fgilio** [spatie/phpunit-snapshot-assertions#103]
Just started using this package yesterday, it's excellent, thanks a lot.
I got the feeling that `--without-creating-snapshots` should be the default, in the sense that stating that your code is working fine should be a deliberate action and not a given.
I actually got some false positives and had to delete some snapshots.

Just my opinion, the package "as is" is perfectly fine.

**Comment by freekmurze** [comment]
I'm thinking the current behaviour is what you'd expect.

By default if there is no snapshot, it will be created. If it already exists, it will be used to compare the result of the currently executed test.
