### ISSUE TITLE
need a way to update snapshots with codecept

### ISSUE THREAD

**Issue by thevikas** [spatie/phpunit-snapshot-assertions#158]
Codeception is not sending the params like phpunit and so have to just manually delete the file for force update. Any ideas?

**Comment by h3ll3r** [comment]
Hi @thevikas, readme states, that it's possible by setting an env variable:
> This is possible by adding a-d --update-snapshots flag to the phpunit command, or setting the UPDATE_SNAPSHOTS env var to true.
