### ISSUE TITLE
Find a way to clean up unused snapshots

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/phpunit-snapshot-assertions#17]
This isn't trivial since it's hard to find out which snapshots are unused, since PHPUnit can be run for a specific test class, or with `--filter`.

Additionally, if #16 is implemented, we need to know more that just the method signature.

**Comment by sebastiandedeyne** [comment]
Closing because stale.

**Comment by mfn** [comment]
Dang. I get the problem with the filter…

I introduced this package to "a big corp testsuite ™️" and ever since I stumble over orphaned snapshots every now and then:
- Cause No. 1: test method renamed
- Cause No. 2: test class renamed
- Cause No. 3: test method removed
- …
