### ISSUE TITLE
Make it usable with docker container

### ISSUE THREAD

**Issue by Niolak** [spatie/phpunit-snapshot-assertions#197]
In our projects, we launch phpunit in a docker container.

User in the docker container is not the same as user in developers laptops. This means that currently the snapshots folders and files cannot be pulled/pushed to git repository without changing permissions manually.

Setting permissions to 777 to folders and files with chmod solves this problem.
(mkdir recursively does not take into account the permission for all the files/folders so it's necessary to chmod folders afterwards)

**Comment by freekmurze** [comment]
We'll continue this in the PRs
