### ISSUE TITLE
Hack-free update flag

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/phpunit-snapshot-assertions#22]
We're currently using PHPUnit's `-d` flag, would be nicer if it was it's own CLI option. phpunit/phpunit#2271 would fix this.

**Comment by Gummibeer** [comment]
https://github.com/sebastianbergmann/phpunit/issues/2271

**Comment by sebastiandedeyne** [comment]
Gonna close this issue, I've lost hope after 3 years.
