### ISSUE TITLE
Should these be in the App namespace?

### ISSUE THREAD

**Issue by jamesmills** [spatie/phpunit-snapshot-assertions#29]
Not sure if this is a big issue or not but I thought I would mention it. We are using your spatie/ssl-certificate package which pulls in this package. 

We already have an  ``App\Order`` in our application and as you reference the App namespace inside vendor/spatie/phpunit-snapshot-assertions/example/composer.json my IDE is picking up that we have two classes named the same in the same namespace.

https://github.com/spatie/phpunit-snapshot-assertions/blob/4b3dcf65c20f8cb925d8de123f6b8d6381bce6df/example/src/Order.php#L3

**Comment by sebastiandedeyne** [comment]
Just released `1.0.2` which should get rid of those files when installing this package through composer.
