### ISSUE TITLE
PHP object driver

### ISSUE THREAD

**Issue by gempir** [spatie/phpunit-snapshot-assertions#46]
It would be really useful to have a more an advanced PHP object driver that would use all public properties and also checks for existing getters and bool methods aswell (like isActive) similar to how the Symfony serializer works.

**Comment by freekmurze** [comment]
Feel free to send a PR.

**Comment by gempir** [comment]
Why are you closing this then? Potential contributors usally look at issues and implement new features by which issues are open.

I don't want to force you/the maintainers of this project to implement this, but I just wanted to have this open for new contributors.
