### ISSUE TITLE
Long file names, not supported characters on windows

### ISSUE THREAD

**Issue by AndreyMashukov** [spatie/phpunit-snapshot-assertions#50]
![image pasted at 2018-9-4 13-02](https://user-images.githubusercontent.com/24682497/45083482-9bff8580-b104-11e8-80ce-23227be7833f.png)
![image pasted at 2018-9-4 14-12](https://user-images.githubusercontent.com/24682497/45083483-9bff8580-b104-11e8-8988-3554d7e4c9e1.png)

I have a problems with file names. Request with fix is created :)

**Comment by AndreyMashukov** [comment]
We need to use this feature, some people use windows in our team, please check !52

**Comment by AndreyMashukov** [comment]
![image](https://user-images.githubusercontent.com/24682497/45088080-a758ae00-b110-11e8-8bcf-f7cc31dd5237.png)

**Comment by sebastiandedeyne** [comment]
We'll continue this conversation in #52
