### ISSUE TITLE
Tests on PHP 7.3 are failing

### ISSUE THREAD

**Issue by freekmurze** [spatie/phpunit-snapshot-assertions#56]
The tests on PHP 7.3 are failing because the output changed in that version of PHP.

Our tests should assert different output for PHP 7.3 so tests on Travis pass for all tested PHP versions.

![image](https://user-images.githubusercontent.com/483853/50178475-e5b35b00-0304-11e9-8044-42e4561dfeaf.png)

**Comment by danielbachhuber** [comment]
Looks like this was fixed in #57 ?
