### ISSUE TITLE
Compatibility with phpunit 8?

### ISSUE THREAD

**Issue by jblotus** [spatie/phpunit-snapshot-assertions#66]

**Comment by freekmurze** [comment]
Upping requirements of dependencies (even PHP) is not a breaking change. We'll probably take care of this soon.

**Comment by DanielBadura** [comment]
A PR for this is already open #65 the one thing that needs to be done there is to remove 7.1 in travis

**Comment by DanielBadura** [comment]
#65 is already merged. Can you say when this change is going into an official release? :)

Thanks! <3

**Comment by sebastiandedeyne** [comment]
Just tagged `2.1.0` :)
