### ISSUE TITLE
Requirement of symfony/yaml ^4.2 is too restrictive

### ISSUE THREAD

**Issue by scheb** [spatie/phpunit-snapshot-assertions#69]
Thanks for the update to make this library compatible with Phpunit 8!

I have a bit of an issue with the requirement symfony/yaml ^4.2, which forces me to update my entire project to Symfony 4.2 (we're on 4.1), just to do a PHPUnit upgrade. symfony/yaml is not doing much, so I'd bet any 4.x or event 3.x version would also work fine for you. So there's actually no need to lock the users of your library into using 4.2+. I'd suggest making the requirement a bit more open and require a reasonable minimum version that is working fine for your use-case, giving people more freedom in which dependencies they use in which version.

**Comment by ebuildy** [comment]
even as ``suggest`` (https://getcomposer.org/doc/04-schema.md#suggest) since this is required only for Yaml driver.

**Comment by sebastiandedeyne** [comment]
Sorry for the late response, missed this issue!

You're right that it's unnecessarily restrictive, I tagged a new version that requires `^4.0`.

**Comment by scheb** [comment]
Thank you :)
