### ISSUE TITLE
Getting "Class not found" errors when this library is installed

### ISSUE THREAD

**Issue by bshaffer** [spatie/phpunit-snapshot-assertions#81]
I am seeing very strange behavior when trying to use this library.

```
$ phpunit test/ReadTest.php 
Class 'test/ReadTest' could not be found in '/myapp/test/ReadTest.php'.
```

`myapp` contains a `phpunit.xml` file that looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap="../testing/bootstrap.php">
    <testsuites>
        <testsuite name="PHP storage test">
            <directory>test</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist>
            <directory suffix=".php">./src</directory>
        </whitelist>
    </filter>
</phpunit>
```

The test cases extend `PHPUnit\Framework\TestCase` and run fine once I remove the dependency on `"spatie/phpunit-snapshot-assertions": "^3.0"`

**Comment by sebastiandedeyne** [comment]
There was probably something off with the project's autoloading. Gonna close this since it's an older issue, but feel free to reopen if there's still a problem :)
