### ISSUE TITLE
Bring back PHP 7.3 support

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [spatie/phpunit-snapshot-assertions#89]
Hi, thanks for the useful tool, but can i ask to bring back support for PHP 7.3? This PHP version is going to be still supported for almost 2 years, also current phpunit (9.0) supports 7.3
Thanks!

**Comment by freekmurze** [comment]
It makes no sense for us to invest time in this, because we don't use the older version of PHP. 

Feel free to use on of the older versions of the package or maintain your own fork that is compatible with the PHP versions you need.
