### ISSUE TITLE
Inconsistent line endings

### ISSUE THREAD

**Issue by nCrazed** [spatie/phpunit-snapshot-assertions#92]
Ran into a problem while on-boarding a developer who's working on Windows: All of the snapshot tests are failing due to `\r\n` instead of the expected `\n`.

Strangely enough, this is also the case when running the tests from within the Linux VM.

**Versions:**

- spatie/phpunit-snapshot-assertions  2.0.0
- Windows 10
- Vagrant 2.2.7
- VirtualBox 6.1.4

I can't tell from the changelog and past issues if this is something that's already been fixed, and we're not currently in the position to upgrade in order to test it.

**Comment by sebastiandedeyne** [comment]
This package hasn't been heavily tested on Windows. We got a PR once, but it involved a _lot_ of changes to get everything working as expected and never got finished…

I'm still open to a PR that adds proper Windows support though.

**Comment by Zutatensuppe** [comment]
@nCrazed i had the same issue, using `assertMatchesHtmlSnapshot` (both in linux vs linux, linux vs mac). Looks like the DOMDocument version is to blame here. I decided to use `assertMatchesSnapshot` instead, works fine :)
