### ISSUE TITLE
Don't automatically create new snapshots when in CI 

### ISSUE THREAD

**Issue by mathieutu** [spatie/phpunit-snapshot-assertions#93]
Hi, 
I had a problem with case insensitive os in local, and case sensitive in CI. 
The result was that all the snapshots was recreated in the CI, and we didn't notice, because the CI was green.

It would be really nice to block the snapshot creation in CI environment.

We can automatically use a package to detect if we are running in CI (found quickly [this one](https://github.com/OndraM/ci-detector)), or let the user block them via a config.

This is related to https://github.com/spatie/phpunit-snapshot-assertions/issues/47#issuecomment-408875107 but not the same, as here, we don't want to skip, but to fail!

Thanks.
Mathieu.

**Comment by freekmurze** [comment]
We'd accept a PR that allows the creation of snapshot to be disabled.

**Comment by mathieutu** [comment]
Add here is the PR @freekmurze! 😉

#94

**Comment by freekmurze** [comment]
Thanks, we'll continue in #94
